# Generated by Django 5.1.4 on 2025-01-15 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('category', models.CharField(choices=[('HYD', 'Hydrogen'), ('SOL', 'Solar'), ('NUC', 'Nuclear'), ('OTH', 'Other')], max_length=3)),
                ('efficiency_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('methodology', models.TextField()),
                ('results', models.TextField()),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('research_paper', models.FileField(upload_to='research_papers/')),
            ],
        ),
        migrations.CreateModel(
            name='ResearcherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('research_field', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='research',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.researcherprofile'),
        ),
    ]
