# Generated by Django 5.1.4 on 2025-01-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_research_researcherprofile_delete_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
