# Generated by Django 5.1.4 on 2025-01-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_researcherprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherprofile',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='other_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
