# Generated by Django 5.1.4 on 2025-01-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_researcherprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherprofile',
            name='academic_title',
            field=models.CharField(choices=[('INT_PHD', 'Integrated PhD'), ('PHD', 'PhD'), ('POST_DOC', 'Post Doctoral'), ('PROF', 'Professor'), ('ASST_PROF', 'Assistant Professor'), ('ASSOC_PROF', 'Associate Professor'), ('RES_SCHOLAR', 'Research Scholar'), ('SCIENTIST', 'Scientist'), ('SR_SCIENTIST', 'Senior Scientist'), ('PRINCIPAL', 'Principal Investigator'), ('OTHER', 'Other')], default='RES_SCHOLAR', max_length=20),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='other_academic_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
